export const questions = [
  'In what city did you meet your first spouse/partner?',
  'In what city did your parents meet?',
  'In what city does your nearest sibling live?',
  'In what city was your father born?',
  'In what city was your first job?',
  'In what city was your mother born?',
  "What city were you in on New Year's 2000?",
  'What is the last name of your favorite teacher in high school?',
  "What is the name of a college you applied to but didn't attend?",
  "What is your father's middle name?",
  'What is your favorite food?',
  "What is your maternal grandmother's first and last name?",
  "What is your mother's middle name?",
  "What is your oldest sibling's middle name?",
  "What is your paternal grandfather's first and last name?",
  "What is your youngest sibling's middle name?",
  'What school did you attend for sixth grade?',
  'What was the first and last name of your childhood best friend?',
  'What was the first and last name of your first significant other?',
  'What was the last name of your favorite grade school teacher?',
  'What was the make and model of your first car or motorcycle?',
  'What was the name of the first school you attended?',
  'What was the name of the hospital in which you were born?',
  'What was the name of the street of your first childhood home?',
  'What was the name of your childhood hero?',
  'What was the name of your favorite stuffed animal?',
  'What was the name of your first pet?',
  'What was your childhood nickname?',
  'What was your favorite sport in high school?',
  'What was your first job?',
  'What were the last four digits of your childhood telephone number?',
  'When you were young, what did you want to be when you grew up?',
  'Who is the most famous person you have ever met?',
];
